from storage.engine import CollectionStore, NOW

COLLECTION_NAME = "economy_settings"
CollectionName = COLLECTION_NAME

_store = CollectionStore(
    name=COLLECTION_NAME,
    defaults={
        "currency_symbol": "฿",
        "start_cash": 0,
        "start_bank": 0,
        "max_cash": 1_000_000_000,
        "max_bank": 1_000_000_000,
        "audit_channel_id": None,
        "command_work_enabled": True,
        "command_slut_enabled": False,
        "command_crime_enabled": False,
        "command_rob_enabled": False,
        "economy_channels_enabled": False,
        "economy_allow_all_channels": True,
        "economy_command_channels": [],
        "work_cooldown": 3600,
        "work_payout_min": 100,
        "work_payout_max": 300,
        "work_fail_rate": 0,
        "work_fine_type": "fixed",
        "work_fine_min": 0,
        "work_fine_max": 0,
        "slut_cooldown": 7200,
        "slut_payout_min": 120,
        "slut_payout_max": 450,
        "slut_fail_rate": 35,
        "slut_fine_type": "fixed",
        "slut_fine_min": 20,
        "slut_fine_max": 150,
        "crime_cooldown": 10800,
        "crime_payout_min": 180,
        "crime_payout_max": 750,
        "crime_fail_rate": 45,
        "crime_fine_type": "fixed",
        "crime_fine_min": 35,
        "crime_fine_max": 260,
        "rob_cooldown": 14400,
        "rob_payout_min": 300,
        "rob_payout_max": 1200,
        "rob_fail_rate": 60,
        "rob_fine_type": "percent",
        "rob_fine_min": 5,
        "rob_fine_max": 25,
        "role_income_enabled": False,
        "role_income_entries": [],
        "chat_money_enabled": False,
        "chat_money_min": 5,
        "chat_money_max": 15,
        "chat_money_cooldown": 60,
        "chat_money_channels": [],
        "items_enabled": False,
        "store_sell_rate": 50,
        "inventory_max_items": 250,
        "custom_replies_enabled": True,
        "work_replies": [],
        "slut_replies": [],
        "crime_replies": [],
        "rob_replies": [],
        "bet_min": 10,
        "bet_max": 100_000,
        "updated_at": NOW,
        "created_at": NOW,
    },
    unique_sets=[["guild_id"]],
    json_fields=set([
        "role_income_entries",
        "chat_money_channels",
        "economy_command_channels",
        "work_replies",
        "slut_replies",
        "crime_replies",
        "rob_replies",
    ]),
    datetime_fields=set(["updated_at", "created_at"]),
    sequence_fields={},
)


async def create_table():
    return await _store.prepare()


async def insert(
    id: int = None,
    guild_id: int = None,
    currency_symbol: str = None,
    start_cash: int = None,
    start_bank: int = None,
    max_cash: int = None,
    max_bank: int = None,
    audit_channel_id: int = None,
    command_work_enabled: bool = None,
    command_slut_enabled: bool = None,
    command_crime_enabled: bool = None,
    command_rob_enabled: bool = None,
    economy_channels_enabled: bool = None,
    economy_allow_all_channels: bool = None,
    economy_command_channels: list = None,
    work_cooldown: int = None,
    work_payout_min: int = None,
    work_payout_max: int = None,
    work_fail_rate: int = None,
    work_fine_type: str = None,
    work_fine_min: int = None,
    work_fine_max: int = None,
    slut_cooldown: int = None,
    slut_payout_min: int = None,
    slut_payout_max: int = None,
    slut_fail_rate: int = None,
    slut_fine_type: str = None,
    slut_fine_min: int = None,
    slut_fine_max: int = None,
    crime_cooldown: int = None,
    crime_payout_min: int = None,
    crime_payout_max: int = None,
    crime_fail_rate: int = None,
    crime_fine_type: str = None,
    crime_fine_min: int = None,
    crime_fine_max: int = None,
    rob_cooldown: int = None,
    rob_payout_min: int = None,
    rob_payout_max: int = None,
    rob_fail_rate: int = None,
    rob_fine_type: str = None,
    rob_fine_min: int = None,
    rob_fine_max: int = None,
    role_income_enabled: bool = None,
    role_income_entries: list = None,
    chat_money_enabled: bool = None,
    chat_money_min: int = None,
    chat_money_max: int = None,
    chat_money_cooldown: int = None,
    chat_money_channels: list = None,
    items_enabled: bool = None,
    store_sell_rate: int = None,
    inventory_max_items: int = None,
    custom_replies_enabled: bool = None,
    work_replies: list = None,
    slut_replies: list = None,
    crime_replies: list = None,
    rob_replies: list = None,
    bet_min: int = None,
    bet_max: int = None,
    updated_at: str = None,
    created_at: str = None,
):
    return await _store.insert(locals())


async def update(
    id: int,
    guild_id: int = None,
    currency_symbol: str = None,
    start_cash: int = None,
    start_bank: int = None,
    max_cash: int = None,
    max_bank: int = None,
    audit_channel_id: int = None,
    command_work_enabled: bool = None,
    command_slut_enabled: bool = None,
    command_crime_enabled: bool = None,
    command_rob_enabled: bool = None,
    economy_channels_enabled: bool = None,
    economy_allow_all_channels: bool = None,
    economy_command_channels: list = None,
    work_cooldown: int = None,
    work_payout_min: int = None,
    work_payout_max: int = None,
    work_fail_rate: int = None,
    work_fine_type: str = None,
    work_fine_min: int = None,
    work_fine_max: int = None,
    slut_cooldown: int = None,
    slut_payout_min: int = None,
    slut_payout_max: int = None,
    slut_fail_rate: int = None,
    slut_fine_type: str = None,
    slut_fine_min: int = None,
    slut_fine_max: int = None,
    crime_cooldown: int = None,
    crime_payout_min: int = None,
    crime_payout_max: int = None,
    crime_fail_rate: int = None,
    crime_fine_type: str = None,
    crime_fine_min: int = None,
    crime_fine_max: int = None,
    rob_cooldown: int = None,
    rob_payout_min: int = None,
    rob_payout_max: int = None,
    rob_fail_rate: int = None,
    rob_fine_type: str = None,
    rob_fine_min: int = None,
    rob_fine_max: int = None,
    role_income_enabled: bool = None,
    role_income_entries: list = None,
    chat_money_enabled: bool = None,
    chat_money_min: int = None,
    chat_money_max: int = None,
    chat_money_cooldown: int = None,
    chat_money_channels: list = None,
    items_enabled: bool = None,
    store_sell_rate: int = None,
    inventory_max_items: int = None,
    custom_replies_enabled: bool = None,
    work_replies: list = None,
    slut_replies: list = None,
    crime_replies: list = None,
    rob_replies: list = None,
    bet_min: int = None,
    bet_max: int = None,
    updated_at: str = None,
    created_at: str = None,
):
    return await _store.update(locals())


async def get(
    id: int = None,
    guild_id: int = None,
    currency_symbol: str = None,
    start_cash: int = None,
    start_bank: int = None,
    max_cash: int = None,
    max_bank: int = None,
    audit_channel_id: int = None,
    command_work_enabled: bool = None,
    command_slut_enabled: bool = None,
    command_crime_enabled: bool = None,
    command_rob_enabled: bool = None,
    economy_channels_enabled: bool = None,
    economy_allow_all_channels: bool = None,
    economy_command_channels: list = None,
    work_cooldown: int = None,
    work_payout_min: int = None,
    work_payout_max: int = None,
    work_fail_rate: int = None,
    work_fine_type: str = None,
    work_fine_min: int = None,
    work_fine_max: int = None,
    slut_cooldown: int = None,
    slut_payout_min: int = None,
    slut_payout_max: int = None,
    slut_fail_rate: int = None,
    slut_fine_type: str = None,
    slut_fine_min: int = None,
    slut_fine_max: int = None,
    crime_cooldown: int = None,
    crime_payout_min: int = None,
    crime_payout_max: int = None,
    crime_fail_rate: int = None,
    crime_fine_type: str = None,
    crime_fine_min: int = None,
    crime_fine_max: int = None,
    rob_cooldown: int = None,
    rob_payout_min: int = None,
    rob_payout_max: int = None,
    rob_fail_rate: int = None,
    rob_fine_type: str = None,
    rob_fine_min: int = None,
    rob_fine_max: int = None,
    role_income_enabled: bool = None,
    role_income_entries: list = None,
    chat_money_enabled: bool = None,
    chat_money_min: int = None,
    chat_money_max: int = None,
    chat_money_cooldown: int = None,
    chat_money_channels: list = None,
    items_enabled: bool = None,
    store_sell_rate: int = None,
    inventory_max_items: int = None,
    custom_replies_enabled: bool = None,
    work_replies: list = None,
    slut_replies: list = None,
    crime_replies: list = None,
    rob_replies: list = None,
    bet_min: int = None,
    bet_max: int = None,
    updated_at: str = None,
    created_at: str = None,
):
    return await _store.get(locals())


async def gets(
    id: int = None,
    guild_id: int = None,
    currency_symbol: str = None,
    start_cash: int = None,
    start_bank: int = None,
    max_cash: int = None,
    max_bank: int = None,
    audit_channel_id: int = None,
    command_work_enabled: bool = None,
    command_slut_enabled: bool = None,
    command_crime_enabled: bool = None,
    command_rob_enabled: bool = None,
    economy_channels_enabled: bool = None,
    economy_allow_all_channels: bool = None,
    economy_command_channels: list = None,
    work_cooldown: int = None,
    work_payout_min: int = None,
    work_payout_max: int = None,
    work_fail_rate: int = None,
    work_fine_type: str = None,
    work_fine_min: int = None,
    work_fine_max: int = None,
    slut_cooldown: int = None,
    slut_payout_min: int = None,
    slut_payout_max: int = None,
    slut_fail_rate: int = None,
    slut_fine_type: str = None,
    slut_fine_min: int = None,
    slut_fine_max: int = None,
    crime_cooldown: int = None,
    crime_payout_min: int = None,
    crime_payout_max: int = None,
    crime_fail_rate: int = None,
    crime_fine_type: str = None,
    crime_fine_min: int = None,
    crime_fine_max: int = None,
    rob_cooldown: int = None,
    rob_payout_min: int = None,
    rob_payout_max: int = None,
    rob_fail_rate: int = None,
    rob_fine_type: str = None,
    rob_fine_min: int = None,
    rob_fine_max: int = None,
    role_income_enabled: bool = None,
    role_income_entries: list = None,
    chat_money_enabled: bool = None,
    chat_money_min: int = None,
    chat_money_max: int = None,
    chat_money_cooldown: int = None,
    chat_money_channels: list = None,
    items_enabled: bool = None,
    store_sell_rate: int = None,
    inventory_max_items: int = None,
    custom_replies_enabled: bool = None,
    work_replies: list = None,
    slut_replies: list = None,
    crime_replies: list = None,
    rob_replies: list = None,
    bet_min: int = None,
    bet_max: int = None,
    updated_at: str = None,
    created_at: str = None,
):
    return await _store.gets(locals())


async def delete(
    id: int = None,
    guild_id: int = None,
    currency_symbol: str = None,
    start_cash: int = None,
    start_bank: int = None,
    max_cash: int = None,
    max_bank: int = None,
    audit_channel_id: int = None,
    command_work_enabled: bool = None,
    command_slut_enabled: bool = None,
    command_crime_enabled: bool = None,
    command_rob_enabled: bool = None,
    economy_channels_enabled: bool = None,
    economy_allow_all_channels: bool = None,
    economy_command_channels: list = None,
    work_cooldown: int = None,
    work_payout_min: int = None,
    work_payout_max: int = None,
    work_fail_rate: int = None,
    work_fine_type: str = None,
    work_fine_min: int = None,
    work_fine_max: int = None,
    slut_cooldown: int = None,
    slut_payout_min: int = None,
    slut_payout_max: int = None,
    slut_fail_rate: int = None,
    slut_fine_type: str = None,
    slut_fine_min: int = None,
    slut_fine_max: int = None,
    crime_cooldown: int = None,
    crime_payout_min: int = None,
    crime_payout_max: int = None,
    crime_fail_rate: int = None,
    crime_fine_type: str = None,
    crime_fine_min: int = None,
    crime_fine_max: int = None,
    rob_cooldown: int = None,
    rob_payout_min: int = None,
    rob_payout_max: int = None,
    rob_fail_rate: int = None,
    rob_fine_type: str = None,
    rob_fine_min: int = None,
    rob_fine_max: int = None,
    role_income_enabled: bool = None,
    role_income_entries: list = None,
    chat_money_enabled: bool = None,
    chat_money_min: int = None,
    chat_money_max: int = None,
    chat_money_cooldown: int = None,
    chat_money_channels: list = None,
    items_enabled: bool = None,
    store_sell_rate: int = None,
    inventory_max_items: int = None,
    custom_replies_enabled: bool = None,
    work_replies: list = None,
    slut_replies: list = None,
    crime_replies: list = None,
    rob_replies: list = None,
    bet_min: int = None,
    bet_max: int = None,
    updated_at: str = None,
    created_at: str = None,
):
    return await _store.delete(locals())


async def get_all():
    return await _store.get_all()

