from storage.engine import CollectionStore, NOW

COLLECTION_NAME = "welcomer_settings"

CollectionName = COLLECTION_NAME

_store = CollectionStore(
    name=COLLECTION_NAME,
    defaults={
        "welcome": False,
        "welcome_message": False,
        "welcome_embed": False,
        "welcome_image": False,
        "welcome_image_theme": "music",
        "welcome_image_theme_url": "",
        "welcome_image_layout_mode": "center_stack",
        "welcome_image_avatar_position": "center",
        "welcome_image_text_align": "center",
        "welcome_image_font_style": "classic",
        "welcome_image_top_text": "ÂÔ¹´ÕµéÍ¹ÃÑº {user}",
        "welcome_image_bottom_text": "à¢éÒÊÙè {server}",
        "invite_tracking_enabled": False,
        "invite_welcome_enabled": False,
        "invite_welcome_template": "ÊÁÒªÔ¡¤¹¹ÕéÁÒ´éÇÂ¤ÓàªÔ­¢Í§ {inviter.mention}  àªÔ­áÅéÇ {inviter.count} ¤¹",
        "invite_welcome_unknown_template": "äÁèÊÒÁÒÃ¶µÃÇ¨ÊÍºä´éÇèÒà¢éÒÁÒ¨Ò¡¤ÓàªÔ­¢Í§ã¤Ã",
        "autorole": False,
        "autoroles_limit": 3,
        "autoroles": [],
        "autonick": False,
        "greet": False,
        "greet_message": "Hello {user.mention} Welcome to {server}",
        "greet_channels": [],
        "greet_delete_after": 5,
        "leave": False,
        "leave_message_enabled": True,
        "leave_embed": False,
        "leave_image": False,
        "leave_message": "{user.mention} ÍÍ¡¨Ò¡ {server} áÅéÇ",
        "leave_embed_title": "{user} left {server}",
        "leave_embed_description": "{user.mention} ÍÍ¡¨Ò¡ {server} áÅéÇ",
        "leave_image_theme": "security",
        "leave_image_theme_url": "",
        "leave_image_layout_mode": "center_stack",
        "leave_image_avatar_position": "center",
        "leave_image_text_align": "center",
        "leave_image_font_style": "classic",
        "leave_image_top_text": "{user}",
        "leave_image_bottom_text": "ÍÍ¡¨Ò¡ {server}",
        "leave_channels": [],
        "leave_delete_after": 0,
        "created_at": NOW,
    },
    unique_sets=[["guild_id"]],
    json_fields=set(["autoroles", "greet_channels", "leave_channels"]),
    datetime_fields=set(["created_at"]),
    sequence_fields={},
    update_cache=("guilds_welcomer_cache", ["guild_id"]),
    delete_cache=("guilds_welcomer_cache", ["guild_id"]),
)


async def create_table():
    return await _store.prepare()


async def insert(
    id: int = None,
    guild_id: int = None,
    welcome: bool = None,
    welcome_channel: int = None,
    welcome_message: bool = None,
    welcome_message_content: str = None,
    welcome_embed: bool = None,
    welcome_image: bool = None,
    welcome_image_theme: str = None,
    welcome_image_theme_url: str = None,
    welcome_image_layout_mode: str = None,
    welcome_image_avatar_position: str = None,
    welcome_image_text_align: str = None,
    welcome_image_font_style: str = None,
    welcome_image_top_text: str = None,
    welcome_image_bottom_text: str = None,
    invite_tracking_enabled: bool = None,
    invite_welcome_enabled: bool = None,
    invite_welcome_template: str = None,
    invite_welcome_unknown_template: str = None,
    welcome_embed_title: str = None,
    welcome_embed_description: str = None,
    welcome_embed_thumbnail: str = None,
    welcome_embed_image: str = None,
    welcome_embed_footer: str = None,
    welcome_embed_footer_icon: str = None,
    welcome_embed_color: str = None,
    welcome_embed_author: str = None,
    welcome_embed_author_icon: str = None,
    welcome_embed_author_url: str = None,
    autorole: bool = None,
    autoroles_limit: int = None,
    autoroles: str = None,
    autonick: bool = None,
    autonick_format: str = None,
    greet: bool = None,
    greet_message: str = None,
    greet_channels: list = None,
    greet_delete_after: int = None,
    leave: bool = None,
    leave_message_enabled: bool = None,
    leave_embed: bool = None,
    leave_image: bool = None,
    leave_message: str = None,
    leave_embed_title: str = None,
    leave_embed_description: str = None,
    leave_image_theme: str = None,
    leave_image_theme_url: str = None,
    leave_image_layout_mode: str = None,
    leave_image_avatar_position: str = None,
    leave_image_text_align: str = None,
    leave_image_font_style: str = None,
    leave_image_top_text: str = None,
    leave_image_bottom_text: str = None,
    leave_channels: list = None,
    leave_delete_after: int = None,
    created_at: str = None,
):
    return await _store.insert(locals())


async def update(
    id: int,
    guild_id: int = None,
    welcome: bool = None,
    welcome_channel: int = None,
    welcome_message: bool = None,
    welcome_message_content: str = None,
    welcome_embed: bool = None,
    welcome_image: bool = None,
    welcome_image_theme: str = None,
    welcome_image_theme_url: str = None,
    welcome_image_layout_mode: str = None,
    welcome_image_avatar_position: str = None,
    welcome_image_text_align: str = None,
    welcome_image_font_style: str = None,
    welcome_image_top_text: str = None,
    welcome_image_bottom_text: str = None,
    invite_tracking_enabled: bool = None,
    invite_welcome_enabled: bool = None,
    invite_welcome_template: str = None,
    invite_welcome_unknown_template: str = None,
    welcome_embed_title: str = None,
    welcome_embed_description: str = None,
    welcome_embed_thumbnail: str = None,
    welcome_embed_image: str = None,
    welcome_embed_footer: str = None,
    welcome_embed_footer_icon: str = None,
    welcome_embed_color: str = None,
    welcome_embed_author: str = None,
    welcome_embed_author_icon: str = None,
    welcome_embed_author_url: str = None,
    autorole: bool = None,
    autoroles_limit: int = None,
    autoroles: str = None,
    autonick: bool = None,
    autonick_format: str = None,
    greet: bool = None,
    greet_message: str = None,
    greet_channels: list = None,
    greet_delete_after: int = None,
    leave: bool = None,
    leave_message_enabled: bool = None,
    leave_embed: bool = None,
    leave_image: bool = None,
    leave_message: str = None,
    leave_embed_title: str = None,
    leave_embed_description: str = None,
    leave_image_theme: str = None,
    leave_image_theme_url: str = None,
    leave_image_layout_mode: str = None,
    leave_image_avatar_position: str = None,
    leave_image_text_align: str = None,
    leave_image_font_style: str = None,
    leave_image_top_text: str = None,
    leave_image_bottom_text: str = None,
    leave_channels: list = None,
    leave_delete_after: int = None,
    created_at: str = None,
):
    return await _store.update(locals())


async def get(
    id: int = None,
    guild_id: int = None,
    welcome: bool = None,
    welcome_channel: int = None,
    welcome_message: bool = None,
    welcome_message_content: str = None,
    welcome_embed: bool = None,
    welcome_image: bool = None,
    welcome_image_theme: str = None,
    welcome_image_theme_url: str = None,
    welcome_image_layout_mode: str = None,
    welcome_image_avatar_position: str = None,
    welcome_image_text_align: str = None,
    welcome_image_font_style: str = None,
    welcome_image_top_text: str = None,
    welcome_image_bottom_text: str = None,
    invite_tracking_enabled: bool = None,
    invite_welcome_enabled: bool = None,
    invite_welcome_template: str = None,
    invite_welcome_unknown_template: str = None,
    welcome_embed_title: str = None,
    welcome_embed_description: str = None,
    welcome_embed_thumbnail: str = None,
    welcome_embed_image: str = None,
    welcome_embed_footer: str = None,
    welcome_embed_footer_icon: str = None,
    welcome_embed_color: str = None,
    welcome_embed_author: str = None,
    welcome_embed_author_icon: str = None,
    welcome_embed_author_url: str = None,
    autorole: bool = None,
    autoroles_limit: int = None,
    autoroles: str = None,
    autonick: bool = None,
    autonick_format: str = None,
    greet: bool = None,
    greet_message: str = None,
    greet_channels: list = None,
    greet_delete_after: int = None,
    leave: bool = None,
    leave_message_enabled: bool = None,
    leave_embed: bool = None,
    leave_image: bool = None,
    leave_message: str = None,
    leave_embed_title: str = None,
    leave_embed_description: str = None,
    leave_image_theme: str = None,
    leave_image_theme_url: str = None,
    leave_image_layout_mode: str = None,
    leave_image_avatar_position: str = None,
    leave_image_text_align: str = None,
    leave_image_font_style: str = None,
    leave_image_top_text: str = None,
    leave_image_bottom_text: str = None,
    leave_channels: list = None,
    leave_delete_after: int = None,
    created_at: str = None,
):
    return await _store.get(locals())


async def gets(
    id: int = None,
    guild_id: int = None,
    welcome: bool = None,
    welcome_channel: int = None,
    welcome_message: bool = None,
    welcome_message_content: str = None,
    welcome_embed: bool = None,
    welcome_image: bool = None,
    welcome_image_theme: str = None,
    welcome_image_theme_url: str = None,
    welcome_image_layout_mode: str = None,
    welcome_image_avatar_position: str = None,
    welcome_image_text_align: str = None,
    welcome_image_font_style: str = None,
    welcome_image_top_text: str = None,
    welcome_image_bottom_text: str = None,
    invite_tracking_enabled: bool = None,
    invite_welcome_enabled: bool = None,
    invite_welcome_template: str = None,
    invite_welcome_unknown_template: str = None,
    welcome_embed_title: str = None,
    welcome_embed_description: str = None,
    welcome_embed_thumbnail: str = None,
    welcome_embed_image: str = None,
    welcome_embed_footer: str = None,
    welcome_embed_footer_icon: str = None,
    welcome_embed_color: str = None,
    welcome_embed_author: str = None,
    welcome_embed_author_icon: str = None,
    welcome_embed_author_url: str = None,
    autorole: bool = None,
    autoroles_limit: int = None,
    autoroles: str = None,
    autonick: bool = None,
    autonick_format: str = None,
    greet: bool = None,
    greet_message: str = None,
    greet_channels: list = None,
    greet_delete_after: int = None,
    leave: bool = None,
    leave_message_enabled: bool = None,
    leave_embed: bool = None,
    leave_image: bool = None,
    leave_message: str = None,
    leave_embed_title: str = None,
    leave_embed_description: str = None,
    leave_image_theme: str = None,
    leave_image_theme_url: str = None,
    leave_image_layout_mode: str = None,
    leave_image_avatar_position: str = None,
    leave_image_text_align: str = None,
    leave_image_font_style: str = None,
    leave_image_top_text: str = None,
    leave_image_bottom_text: str = None,
    leave_channels: list = None,
    leave_delete_after: int = None,
    created_at: str = None,
):
    return await _store.gets(locals())


async def delete(
    id: int = None,
    guild_id: int = None,
    welcome: bool = None,
    welcome_channel: int = None,
    welcome_message: bool = None,
    welcome_message_content: str = None,
    welcome_embed: bool = None,
    welcome_image: bool = None,
    welcome_image_theme: str = None,
    welcome_image_theme_url: str = None,
    welcome_image_layout_mode: str = None,
    welcome_image_avatar_position: str = None,
    welcome_image_text_align: str = None,
    welcome_image_font_style: str = None,
    welcome_image_top_text: str = None,
    welcome_image_bottom_text: str = None,
    invite_tracking_enabled: bool = None,
    invite_welcome_enabled: bool = None,
    invite_welcome_template: str = None,
    invite_welcome_unknown_template: str = None,
    welcome_embed_title: str = None,
    welcome_embed_description: str = None,
    welcome_embed_thumbnail: str = None,
    welcome_embed_image: str = None,
    welcome_embed_footer: str = None,
    welcome_embed_footer_icon: str = None,
    welcome_embed_color: str = None,
    welcome_embed_author: str = None,
    welcome_embed_author_icon: str = None,
    welcome_embed_author_url: str = None,
    autorole: bool = None,
    autoroles_limit: int = None,
    autoroles: str = None,
    autonick: bool = None,
    autonick_format: str = None,
    greet: bool = None,
    greet_message: str = None,
    greet_channels: list = None,
    greet_delete_after: int = None,
    leave: bool = None,
    leave_message_enabled: bool = None,
    leave_embed: bool = None,
    leave_image: bool = None,
    leave_message: str = None,
    leave_embed_title: str = None,
    leave_embed_description: str = None,
    leave_image_theme: str = None,
    leave_image_theme_url: str = None,
    leave_image_layout_mode: str = None,
    leave_image_avatar_position: str = None,
    leave_image_text_align: str = None,
    leave_image_font_style: str = None,
    leave_image_top_text: str = None,
    leave_image_bottom_text: str = None,
    leave_channels: list = None,
    leave_delete_after: int = None,
    created_at: str = None,
):
    return await _store.delete(locals())


async def get_all():
    return await _store.get_all()


